### PR TITLE
users' last activity (status) time in 'who to follow' lists

### PR DESCRIPTION
**Pull request by erqan**

### CODE REVIEW

**Comment by erqan** [comment]
last-activity-in-who-to-follow

last-activity-in-following-list

**Comment by miguelfreitas** [comment]
looks good to me. what do you think @slr ?

**Comment by slr** [comment]
I think I should answer quicker. my bad.

on subject: even though it looks a bit messy [for me] right now — of course it's helpful to display time of latest activity.

I have to suggest [this](https://github.com/erqan/twister-html/pull/1) and then let's go further.

**Comment by slr** [comment]
@erqan

**Pull request merged**
