### PR TITLE
retwist with comment

### PR DESCRIPTION
**Pull request by slr**
comment editing
regular retwist and same with comment

### CODE REVIEW

**Comment by slr** [comment]
post retwists with comment as posts with citation

**Comment by slr** [comment]
it requires miguelfreitas/twister-core#345 and twisterd version number increasion.

**Comment by slr** [comment]
ok, now it's good enough to not affraid to test a lil' somethin'.

**Comment by slr** [comment]
I suppose it even may be merged, if you will not find any critical bugs of course. peers will be able to see my and @erqan's posted commented retwists and then — again *after merging of miguelfreitas/twister-core#345 and increasing of twisterd version* — they will be able to send their own ones.

**Comment by erqan** [comment]
@slr on **chromium** *retransmit* button makes *RT*, but *post* button send the message as **reply**..

**Comment by slr** [comment]
@erqan fixed.

**Comment by slr** [comment]
@erqan fixed.

**Pull request merged**
