### PR TITLE
Global back button in modal

### PR DESCRIPTION
**Pull request by Tschaul**
This pull request is in regard to issue #199. I implemented a back button with which one can navigate back through hashtag, profile, mentions, conversation, whotofollow and directmessages modals. Also the browsers back as well as forward button work for navigating between these. I have put the other three modals (reply, retwist and follow) on to a separate popup layer (called "prompt"), so that they do not interfere with the navigation. The prompt has a dark heading background to make it visually distinct from the modal. I tweaked the modals in the original theme to have the same size and rounded corners, in order to have a smoother navigation between modals. The back button also works in nin and calm theme. For the nin theme I needed to add a compass config file to have it compile on my machine.

Please give it a test-drive!

### CODE REVIEW

**Comment by Tschaul** [comment]
With the method with which I just fixed that bug it is also possible to implement a forward button, that is only visible if there you went back before. But I don't know how the buttons should be arranged then.

**Comment by miguelfreitas** [comment]
@Tschaul you sure you pushed the right patch? i've tried this PR and it breaks with:

Uncaught SyntaxError: Unexpected token ) interface_common.js:407

**Comment by miguelfreitas** [comment]
Fantastic work!

**Comment by Tschaul** [comment]
Thank you! Sorry for that syntax error, don't understand how it got into the commit.

**Pull request merged**
