### PR TITLE
initial commit of desktop notifications 

### PR DESCRIPTION
**Pull request by slr**
here is desktop notifications with counter of new posts which are appearing in postboard, new direct messages and posts in modal window of searching of hashtags and of mentions. icon of them is twister logo. clicking on notifications shows new entries with openning modal windows if it is necessary.

there was added test button to `options.html`. if does error alert appear when you click on it then probably notifications do not permitted in browser settings.
_Sound_ tab of options was renamed in _Notifications_.

notify.js by @alexgibson from https://github.com/alexgibson/notify.js
we are able to easy modify or tune it since it is very simple. _keep in mind that specs of notifications are not finished at stone (last changes of [standard](https://notifications.spec.whatwg.org) dated of January 17) and therefore current implementation is kind of experimental stuff_.

I tested it on Firefox and Opera-Webkit. both of them have issues wth timeout of showing: Firefox hides notifications too fast but Opera may never hide them with 10 seconds of timeout.

fixed playing sound notification of direct messages.

### CODE REVIEW

**Comment by slr** [comment]
removed notifications when sending own posts (not only desktop notifications but on top of postboard too) or DMs
removed duplicate message about post sending (which was without localization also)
added some localization lines

fixed hashtag searching from that bar on top

**Comment by miguelfreitas** [comment]
cool stuff! unfortunately it didn't worked here (tried both firefox 34 and chrome 38)
any idea? "unknown error occurred" is not much helpful ;-)

**Comment by slr** [comment]
added requesting of permission when any notifications are showing if permission level is _default_
fixed behaviour when permission denied so now there is no alert about unlnown error when permission is denied or not defined
fixed alerts lines

[pull request](https://github.com/alexgibson/notify.js/pull/32) sended to `notify.js` repository

it is definitely working on last Firefox Nightly and Opera Developer builds (so I suppose it is working on Chrome too), but Opera has issue: when you deny permission it does not update permission level from default to denied until page reloading and it does not ask you about that at same time so you have not any alerts about permission denial when you are clicking on test button until you reload the page.

**Comment by slr** [comment]
yet another kind of issue with requesting of permission is in fact that requesting does not stop page actions so currently we do not see notification which asked permission anyway.

**Comment by slr** [comment]
@miguelfreitas wait for evening. I had some conversation on that pull request which I talked about above, so I should fix some things.

**Comment by slr** [comment]
done in more proper and convenient way. functionality is the same.

**Comment by miguelfreitas** [comment]
Great! now it works, thanks!

**Pull request merged**
