### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by xfq**
* Mac OS X -> OS X
* Markup and punctuation fixes

### CODE REVIEW

**Comment by slr** [comment]
@xfq please, fix same in 'blaster' branch.

@miguelfreitas could you review and merge current progress in 'blaster' to update pull requests accepting policy (see https://github.com/miguelfreitas/twister-html/compare/blaster#diff-04c6e90faac2675aa89e2176d2eec7d8R34) to avoid merging conflicts in future?

**Comment by xfq** [comment]
@slr Should I create a new PR (for the current fix) against the `baster` branch?

**Comment by slr** [comment]
@xfq it's hard to apply this commit to https://github.com/miguelfreitas/twister-html/blob/blaster/README.md because of `e` in `You're` and long dash `—` instead `-` there. so I ask you to make new fix starting right from 'blaster' current state and exactly for 'blaster' itself. all commits in it will be merged to `master` in future. sorry for this issue, we are in period of transition currently.

**Comment by xfq** [comment]
@slr I see.  Thanks for your explanation!

I'll create my PRs against the `blaster` branch in the future.

**Pull request merged**
