### PR TITLE
show rt-comments

### PR DESCRIPTION
**Pull request by erqan**
read-only...

### CODE REVIEW

**Comment by erqan** [comment]
preview...

**Comment by slr** [comment]
I don't like it. I'm used to think about it in Twitter way as citation thing.

**Comment by erqan** [comment]
yes, it's possible to design better.. but i think original post should be more visible.. 


Erkan Yüksel

11 Ağu 2015 tarihinde 21:18 saatinde, Сёма Мрачный <notifications@github.com> şunları yazdı:

**Comment by slr** [comment]
I'll take care about this entirely if you don't mind. but I want to clear the things before that: #294

**Comment by erqan** [comment]
ok, it's yours...

**Pull request closed without merging**
