### PR TITLE
language filtering and other various things for timeline updating

### PR DESCRIPTION
**Pull request by slr**
I'm in preparing of filtering by language. and currently:
  * we cache new postboard posts for time in which timeline update request will be
    * so we don't request and filter postboard posts twice, we show them immediately instead
  * we don't request timeline updates for _posts sended in current session by ourself_ by timeout, we show that posts right after confirmation

### CODE REVIEW

**Comment by slr** [comment]
ok, now there are:
  * language filtering for postboard
    * we are using `franc.js` from https://github.com/wooorm/franc with supporting of 75 languages
      * we could select from 3 versions of it with supporting of 75, 175 or 175 languages, it is question of size
      * as I see now it is a bit obsolete, because I have downloaded it about 6 days ago but it was updated 4 days ago; it will be updated ASAP
    * we may filter somewhat by 2 methods
      * blacklisting, that means that we hide all posts which have text with language that is in blacklist
        * I recommend this mode because many reasons. first `franc.js` is not perfect (oh, it's very good but problem of language recognition is too comlicated) so in case of whitelisting you can miss many various posts, e.g. post like _`No, but it looks cute`_ with only _`eng`_ whitelisted may be hidden as too french
      * whitelisting, that means that we show all posts which have text with language that is in whitelist
        * currently if language of post is undefined it will be shown in this mode anyway
    * common language posts like ones with only digits will be passed and shown always
    * we cut out any mentions, links and # symbols from hashtags before filtering
      * maybe we need to cut out hashtags completely
    * we are able to test filtering in simulation mode
      * no posts are hidden, some major data of filtering appends to end of each post (mplementation is raw currently)
  * options of this in `Postboard displays` section of `options.html`
    * we can select filtering method
    * we able to provide a list of separated ISO 639-3 language codes to filter
    * we may set up accuracy of filtering (some insights about this thing may be available [there](http://wooorm.github.io/franc/))
      * I suppose we need same thing as part of these options
  * fixes of requesting scheme
  * smaller text size for inputs, selects and buttons for options of theme `nin`

**Comment by slr** [comment]
there are:
* updated `franc.js`, thanks to @wooorm
  * [added](https://github.com/wooorm/franc/commit/c90f51e6c817f402f68a9a254b6125d0273f1552): _minLength_ support
  * [fixed](https://github.com/wooorm/franc/issues/18): digits-only strings that is treated as _`cmn`_
* localization of language filter strings for Chinese, French, German and Russian, thanks to `@chinanet`, @myleneb and `@vegos`
  * was used [pad.riseup.net](https://pad.riseup.net/p/uZuVyPVqgich)
* fixes of filtering
  * fix of my fault with _`cmn`_ that is not common actually
  * fix of splitting of _filterLangList_ string of option
  * some optimization of _willBeHidden()_
  * default value _filterLangAccuracy_ changed from 0.63 to 0.82. maybe we need to set up it as 0.5 by default and place some clearly explanation around it
    * higher values is better for filtering by blacklisting because more posts that can be detected as related to too wide range of languages would avoid hiding
      * but if accuracy is set to 1 then many unwanted posts are allowed by reason of frequent wrong detection
    * a bit lower values is better for filtering by whitelisting because more posts that can be detected as related to too wide range of languages also would avoid hiding
      * but if accuracy is set to too small value then many unwanted posts would be allowed

**Comment by slr** [comment]
there are some screens:
options
in postboard 1
in postboard 2

as you can see value of _filterLangAccuracy_ is too picky for our cute french friend.

**Comment by miguelfreitas** [comment]
Great job! I just tried it in simulation mode, it is very cool! I think you did pretty good decisions on which configuration options to add (white/black list, accuracy and simulation).

Do you think it is ready/stable for merging?

The only missing feature (imho) is to allow filtering the Top Trends as well.

**Comment by slr** [comment]
it is pretty stable and almost ready. I suppose it may be merged anyway because it is optional thing and disabled by default.

things to do:
* workaround to not filter retwists of our own posts
* filtering of Top Trends
  * do we need activation checkbox for this?
* filtering of hashtags search results
  * do we need activation checkbox for this?
* personal filtering settings for any user with customization of it in configuration of following pop-up
* ability of quick confuguration of filter on any page
* optional mode of caching of blocked posts
  * in this mode blocked posts may be represent as line with height of 2-4 px
    * if we click on it then blocked post appears from cache
    * close lines may be grouped and some indicator may show their count

**Comment by slr** [comment]
- [x] workaround to not filter retwists of our own posts
- [x] filtering of Searching 
- [x] filtering of Top Trends, thanks to @iHedgehog for name of _updateTrendingHashtags()_ function
- [x] checkboxes for all currently implemented scopes of filtering
  - [ ] TODO: translation of that
  - [ ] FIXME: checkbox of Simulation mode in `nin` theme is going off-road a bit
- [x] autoupdating of Top Trends in 2 minutes
  - [ ] TODO: option for that
- [x] localization for Turkish, thanks to `@rysiek` (or maybe not to him, but to him for localization for Polish and possible upcoming whole Twister translation to Polish)

options
searching

**Comment by miguelfreitas** [comment]
I'm getting an error here:
twister_timeline.js:395 Uncaught TypeError: Cannot read property 'pass' of undefined
interface_home.js:138 Uncaught TypeError: Cannot read property 'pass' of undefined

**Comment by slr** [comment]
sorry, I forgot about a few checks in last commit. give me some time to finish.

**Comment by slr** [comment]
in short there are:
* fixes of
  * language filtering
  * posts showning
  * localization, especially for Chinese, French, German and Russian
    * team worked [hard](https://pad.riseup.net/p/uZuVyPVqgich/timeslider#1696), many thanks to `@chinanet`, @myleneb and `@vegos`
* option for autoupdating of Top Trends
  * on the subject of options
    * now we want positive numbers for number fields
    * module `Postboard` was renamed to `Appearance`
* some related updates of CSS and SASS for `nin` theme

nin options
_note: of course it is not technically correct to place comments inside that field. just a demo_

**Comment by black-puppydog** [comment]
Some minor tweaks come to mind when using this:

1. Add example codes to the form label. I started with 'en,de,fr,sv' because frankly, ISO-XYZ doesn't speak to me.
2. Make 'passed' and 'blocked' be green and red in simulation mode.
3. What does accuracy mean? How accurate the language filter should be? 100% of course! But I guess then we wouldn't need a setting. So a small explanation would be cool :)

Apart from that I love it, thanks! :)

**Comment by slr** [comment]
@black-puppydog sorry for a such of delay. maybe we'll return to it soon.

about 3rd I said above:

>    * we may set up accuracy of filtering
>      * some insights about this may be available [there](http://wooorm.github.io/franc/)
>        * I suppose we need same sandbox thing as part of these options

**Pull request merged**
