### PR TITLE
sync with blaster

### PR DESCRIPTION
**Pull request by slr**
@miguelfreitas looks like it's quite stable and it has fixes for some issues like these ones:
* https://github.com/miguelfreitas/twister-html/issues/277
* https://github.com/miguelfreitas/twister-html/issues/344
* https://github.com/miguelfreitas/twister-html/pull/347

I'll continue to work on https://github.com/miguelfreitas/twister-html/issues/338 soon and after that, most probably, on favorites.

### CODE REVIEW

**Comment by slr** [comment]
@miguelfreitas I recommend to merge this as soon as possible because for now at `master` branch timeline of some users may be filled with empty twists without https://github.com/miguelfreitas/twister-html/pull/348/commits/cfd51f163ed8e9a0e23e41cd0417135eb7c259e2 and https://github.com/miguelfreitas/twister-html/pull/348/commits/9fcadc96340ec08d3321e0abf2c0e50a510d3f4f and even completely broken without https://github.com/miguelfreitas/twister-html/pull/348/commits/a26ff53c762ac7daf9f54a264b5f6ef9b52e2a8c.

**Comment by miguelfreitas** [comment]
Great! thanks for your work! I'm merging now.

PS: I expect to work on longer posts this weekend :-)

**Comment by slr** [comment]
@miguelfreitas yep, sounds good excepting a word 'post'. I prefer 'twist' instead. and, looks like, the twist is not so empty if it contains something. `s/empty post/'empty' twist` and I'm fine.

meanwhile, see https://github.com/miguelfreitas/twister-html/pull/349

**Comment by miguelfreitas** [comment]
Sure, agreed with `s/empty post/'empty' twist`!

**Comment by slr** [comment]
@miguelfreitas ok, https://github.com/miguelfreitas/twister-html/pull/350. I bet that you specially choose longer phrases to make short prompt's input field longer.

**Comment by miguelfreitas** [comment]
Actually I guessed you would disagree and suggest something shorter, but then you just replaced a single word ;-)

**Comment by slr** [comment]
@miguelfreitas I feel like I'm able to edit that silently when you don't see, haha. see, you say
> This special post is not displayed by twister clients

but in fact it's not displayed only by *modern* clients.

to be serious, I only want to be -less serious- more informal in GUI elements where it's not inpacting on security.

**Pull request merged**
